version = "1.0"

[generator]
mode = "sample"
count = 3
speed = 1000
parallel = 2

# [output]
# connect = "file_raw_sink"

# [output.params]
# base = "data/in_dat"
# file = "gen.dat"


[output]
# 仅当存在 connect 时，其他 output 字段和旧式 [output.*] 子块将被忽略
name = "gen_out"
connect = "tcp_sink"
params = { port= 19002 }

[logging]
level = ""
module_levels = []
output = ""
file_path = "./data/logs"