service:
  flush: 1
  daemon: off
  log_level: info
  http_server: on
  http_listen: 0.0.0.0
  http_port: 2020

env:
  VAULTWARDEN_CONTAINER_NAME: vaultwarden
  VAULTWARDEN_APP_NAME: vaultwarden
  CADDY_CONTAINER_NAME: caddy
  CADDY_APP_NAME: caddy

pipeline:
  inputs:
    # 密码服务日志
    - name: tail
      path: /host/var/lib/docker/containers/*/*.log
      path_key: filename
      refresh_interval: 5
      skip_long_lines: on
      tag: docker.app.*

  filters:
    # 添加容器名信息
    - name: lua
      match: 'docker.app.*'
      script: ./script/docker-utils.lua
      call: extract_container_name

    # 只保留容器名=vaultwarden和caddy的
    - name: grep
      match: 'docker.app.*'
      logical_op: or
      regex: 
        - container_name ${VAULTWARDEN_CONTAINER_NAME}
        - container_name ${CADDY_CONTAINER_NAME}

    # 将容器名提供到tag中
    - name: rewrite_tag
      match: 'docker.app.*'
      rule: $container_name .* retag.docker.app.$container_name false

    # 添加密码服务相关业务字段
    - name: modify
      match: retag.docker.app.${VAULTWARDEN_CONTAINER_NAME}
      add:
        - app_name ${VAULTWARDEN_APP_NAME}

    # 添加相关业务字段
    - name: modify
      match: retag.docker.app.${CADDY_CONTAINER_NAME}
      add:
        - app_name ${CADDY_APP_NAME}

    # 添加相关业务字段
    - name: modify
      match: '*'
      add: 
        - host_name ${HOSTNAME}

  outputs:
    - name: tcp
      match: "*"
      host: ${CENTRE_HOST_IP}
      port: 19002
      format: json_lines