services:

  warp-parse:
    image: ghcr.io/wp-labs/warp-parse:0.21.4-alpha
    container_name: warp-parse
    restart: unless-stopped
    ports:
      - "19002:19002"
    volumes:
      - ./wparse:/data
    entrypoint: ["/bin/sh", "-c"]
    command: ["cd /data && wparse deamon"]


  wp-monitor:
    image: ghcr.io/wp-labs/wp-monitor:0.2.2-alpha
    container_name: wp-monitor
    restart: unless-stopped
    ports:
      - "18080:18080"
    environment:
      APP_CONFIG_PATH: /app/config/app.toml
    volumes:
      - ./wp-monitor/config:/app/config:ro

  victoria-metrics:
    container_name: victoria-metrics
    image: victoriametrics/victoria-metrics:v1.133.0
    ports:
      - "8428:8428"
    volumes:
      # 数据存储目录，按需开启
      - metrics_data:/storage
    command:
      - --envflag.enable
      - --envflag.prefix=VM_
      - --loggerFormat=json
      - --retentionPeriod=${RETENTION_PERIOD}
      - --storageDataPath=/storage
    environment:
      - TZ=Asia/Shanghai
    # 健康检查
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://127.0.0.1:8428/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  victoria-logs:
    container_name: victoria-logs
    image: victoriametrics/victoria-logs:v1.43.0
    ports:
      - "9428:9428"
    # 数据存储目录,按需开启
    volumes:
      - logs_data:/storage
    command:
      - --envflag.enable
      - --envflag.prefix=VLOGS_
      - --http.shutdownDelay=15s
      - --httpListenAddr=:9428
      - --loggerFormat=json
      - --retentionPeriod=${RETENTION_PERIOD}
      - --storageDataPath=/storage
    environment:
      - TZ=Asia/Shanghai
    # 添加健康检查
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://127.0.0.1:9428/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  logs_data:
    driver: local
  metrics_data:
    driver: local
