services:
  fluent-bit:
    image: fluent/fluent-bit:4.0.3 # 选择你需要的版本
    container_name: fluent-bit
    working_dir: /fluent-bit/etc
    restart: always
    env_file:
      - ./.env
    environment:
      - FLB_LOG_LEVEL=info
    volumes:
      # 挂载配置文件
      - ./fluent-bit:/fluent-bit/etc
      # 宿主机日志目录
      - /var/log:/var/log:ro
      # Docker 容器日志目录
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      # 系统时区（可选）
      - /etc/localtime:/etc/localtime:ro
        # 系统时区（可选）
      - /etc/machine-id:/etc/machine-id:ro
      - /:/host:ro
    command: >
      /fluent-bit/bin/fluent-bit
      -c /fluent-bit/etc/fluent-bit.yml

  warp-parse:
    user: "root"
    image: ghcr.io/wp-labs/warp-parse:0.21.7-alpha
    container_name: warp-parse
    restart: unless-stopped
    ports:
      - "19002:19002"
    volumes:
      - ./wparse:/data
    entrypoint: ["wparse", "deamon", "--work-root", "/data"]

  wp-monitor:
    image: ghcr.io/wp-labs/wp-monitor:0.3.2-alpha
    container_name: wp-monitor
    restart: unless-stopped
    ports:
      - "18080:18080"
    environment:
      APP_CONFIG_PATH: /app/config/app.toml
    volumes:
      - ./wp-monitor/config:/app/config:ro

  victoria-metrics:
    container_name: victoria-metrics
    image: victoriametrics/victoria-metrics:v1.133.0
    ports:
      - "8428:8428"
    volumes:
      # 数据存储目录，按需开启
      - metrics_data:/storage
    command:
      - --envflag.enable
      - --envflag.prefix=VM_
      - --loggerFormat=json
      - --retentionPeriod=${RETENTION_PERIOD}
      - --storageDataPath=/storage
    environment:
      - TZ=Asia/Shanghai
    # 健康检查
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://127.0.0.1:8428/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  victoria-logs:
    container_name: victoria-logs
    image: victoriametrics/victoria-logs:v1.43.0
    ports:
      - "9428:9428"
    # 数据存储目录,按需开启
    volumes:
      - logs_data:/storage
    command:
      - --envflag.enable
      - --envflag.prefix=VLOGS_
      - --http.shutdownDelay=15s
      - --httpListenAddr=:9428
      - --loggerFormat=json
      - --retentionPeriod=${RETENTION_PERIOD}
      - --storageDataPath=/storage
    environment:
      - TZ=Asia/Shanghai
    # 添加健康检查
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://127.0.0.1:9428/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  blackbox-exporter:
    image: quay.io/prometheus/blackbox-exporter:v0.28.0
    container_name: blackbox-exporter
    restart: unless-stopped
    ports:
      - "9115:9115"
    volumes:
      - ./blackbox.yml:/etc/blackbox_exporter/config.yml:ro
    command:
      - --config.file=/etc/blackbox_exporter/config.yml

volumes:
  logs_data:
    driver: local
  metrics_data:
    driver: local
